controller:
  host: '127.0.0.1'
  port: 11000

ASRPipelineConfig:
  enable: true
  server_url: "http://127.0.0.1:11001"
  sample_rate: 16000
  channels: 1
  format: float32

LLMPipelineConfig:
  enable: true
  server_url: "http://127.0.0.1:11002"

ImgCapPipelineConfig:
  enable: true
  server_url: "http://127.0.0.1:11003"

OCRPipelineConfig:
  enable: true
  server_url: "http://127.0.0.1:11004"

VidCapPipelineConfig:
  enable: true
  server_url: "http://127.0.0.1:11005"

TTSPipelineConfig:
  enable: true
  server_url: "http://127.0.0.1:11006"

LiveStreamConfig:
  enable: true
  platform: bilibili
  room_id: null
  credential:
    # [More details](https://nemo2011.github.io/bilibili-api/#/get-credential)
    sessdata: null
    bili_jct: null
    buvid3: null

GameBridgeConfig:
  enable: true
  host: '127.0.0.1'
  port: 11007
  platform: minecraft
