# Bilibili 直播配置
BilibiliLiveConfig:
  # 获取方式[详见](https://nemo2011.github.io/bilibili-api/#/get-credential)
  SESSDATA: SESSDATA
  bili_jct: bili_jct
  buvid3: buvid3
# ChatGLM3 服务配置
ChatGLM3ServiceConfig:
  # 是否以调试模式运行
  debug: False
  # ChatGLM3 服务地址
  host: 127.0.0.1
  # ChatGLM3 服务端口
  port: 8721
  # Tokenizer 路径
  tokenizer_path: /
  # 模型路径
  model_path: /
  # 量化
  quantize: 4
