开心:
  refer_wav_path: /
  prompt_text: /,
  prompt_language: /
伤心:
  refer_wav_path: /
  prompt_text: /,
  prompt_language: /
生气:
  refer_wav_path: /
  prompt_text: /,
  prompt_language: /
羞耻:
  refer_wav_path: /
  prompt_text: /,
  prompt_language: /
害怕:
  refer_wav_path: /
  prompt_text: /,
  prompt_language: /
嘲讽:
  refer_wav_path: /
  prompt_text: /,
  prompt_language: /