# Note: Please rename this file to global_config.yaml to take effect

# Live-streaming Service Configuration
live_stream:
  # Whether to start this service
  enable: True
  platforms:
    # Bilibili platform configuration
    - bilibili:
        # Method of obtaining credentials [See here](https://nemo2011.github.io/bilibili-api/#/get-credential)
        sessdata:
        bili_jct:
        buvid3:
        # Live room ID (must be a number)
        room_id:

# Screenshot Service Configuration
screenshot:
  # Whether to start this service
  enable: True
  # Window title (will automatically find the first window that matches this title)
  window_title: Minecraft
  # Scaling factor (to prevent the screen from capturing the window)
  k: 0.9
  # Location where the captured images are stored
  save_directory: .tmp/screenshots

# Image-Captioning Service Configuration
image_captioning:
  # Whether to start this service
  enable: True
  # Whether to run in debug mode
  debug: False
  # Web service address
  host: 127.0.0.1
  # Web service port
  port: 9879
  # Supported image-captioning models
  models:
    - Salesforce/blip-image-captioning-large:
        # Path of the BLIP model
        model_path: Salesforce/blip-image-captioning-large
        # Default text prompt for BLIP
        text_prompt: There

# Text-to-Speech Service Configuration
text_to_speech:
  # Whether to start this service
  enable: True
  # Whether to run in debug mode
  debug: False
  # Web service address
  host: 127.0.0.1
  # Web service port
  port: 9880
  # Location where the generated wav files are stored
  save_directory: .tmp/wav_output
  # Supported text-to-speech models
  models:
    - RVC-Boss/GPT-SoVITS:
      # There is no need to configurate because the script of GPT-SoVTIS is in its project
      # But please do not delete this item because ZerolanLiveRobot depends on this item to choose model format

# LLM Service Configuration
large_language_model:
  # Whether to start this service (must be True)
  enable: True
  # Whether to run in debug mode
  debug: False
  # LLM service address
  host: 127.0.0.1
  # Web service port
  port: 9881
  # Supported LLMs
  models:
    - THUDM/chatglm3-6b:
        model_path: THUDM/chatglm3-6b
        quantize: 4
    - Qwen/Qwen-7B-Chat:
        model_path: Qwen/Qwen-7B-Chat
        quantize: 4
        loading_mode: auto
    - 01-ai/Yi:
        model_path: 01-ai/Yi
        loading_mode: auto
    - augmxnt/shisa-7b-v1:
        model_path: augmxnt/shisa-7b-v1
        loading_mode: auto

# Tone Analysis Service Configuration
tone_analysis:
  # Whether to start this service (If true, LLM service and TTS service must be both enabled)
  enable: True
  # Path of tone analysis template file
  tone_analysis_template_path: template/tone_ayalysis_template.yaml

# OBS Service Configuration
obs:
  # Whether to start this service
  enable: True
  # Output subtitle file for danmaku
  danmaku_output_path: .tmp/danmaku_output/output.txt
  # Output subtitle file for tone
  tone_output_path: .tmp/tone_output/output.txt
  # Output subtitle file for the LLM
  llm_output_path: .tmp/llm_output/output.txt

# VAD Service Configuration
voice_activity_detection:
  # Whether to start this service
  enable: True
  # Location to save user voice
  save_directory: .tmp/records
  # Block size
  chunk: 4096
  # Sample rate
  sample_rate: 16000
  # Activation threshold
  threshold: 600
  # Maximum allowed silence count
  max_mute_count: 10

# ASR Service Configuration
auto_speech_recognition:
  # Whether to start this service
  enable: True
  # Whether to start this service
  debug: False
  # ASR service address
  host: 127.0.0.1
  # ASR service port
  port: 9882
  # Supported ASR models
  models:
    - speech_paraformer:
        model_path:
        version: v2.0.4

# Minecraft Service Configuration
minecraft:
  enable: True

# Zerolan Live Robot Configuration
zerolan_live_robot_config:
  # Whether to start this service
  enable: True
  # Whether to start this service
  debug: False
  # Zerolan Live Robot service address
  host: 127.0.0.1
  # Zerolan Live Robot service port
  port: 9888
  # Path of role play template
  role_play_template_path: template/role_play_template_short.yaml

